# SPDX-FileCopyrightText: 2025 Blu
# SPDX-FileCopyrightText: 2025 UnicornOnLSD
# SPDX-FileCopyrightText: 2025 starch
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: playTimeTracker
  id: JobUSSPCommissar

- type: playTimeTracker
  id: JobUSSPCorporal

- type: playTimeTracker
  id: JobUSSPMedic

- type: playTimeTracker
  id: JobUSSPRifleman

- type: playTimeTracker
  id: JobUSSPSergeant

- type: playTimeTracker
  id: JobTsfEngineer

- type: playTimeTracker
  id: MdMedic

# DI Jobs

- type: playTimeTracker
  id: JobDIPOverseer
    
- type: playTimeTracker
  id: JobDIWatchdog
  
- type: playTimeTracker
  id: JobDITrucker

- type: playTimeTracker
  id: JobDIGrunt