# Base prototypes

- type: latheRecipe
  abstract: true
  id: BaseWeaponRecipe
  categories:
  - Weapons
  completetime: 2
  materials:
    Steel: 300
    Plastic: 300

- type: latheRecipe
  abstract: true
  parent: BaseWeaponRecipe
  id: BaseWeaponRecipeLong
  completetime: 5

- type: latheRecipe
  abstract: true
  id: BaseAmmoRecipe
  categories:
  - Ammo
  completetime: 5

- type: latheRecipe
  abstract: true
  parent: BaseAmmoRecipe
  id: BaseEmptyAmmoRecipe
  completetime: 1

# Recipes

- type: latheRecipe
  id: Handcuffs
  result: Handcuffs
  completetime: 2
  materials:
    Steel: 300

- type: latheRecipe
  id: Zipties
  result: Zipties
  completetime: 2
  materials:
    Plastic: 200

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: Stunbaton
  result: Stunbaton

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: Truncheon
  result: Truncheon

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: CombatKnife
  result: CombatKnife
  materials:
    Steel: 250
    Plastic: 100

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponLaserCarbine
  result: WeaponLaserCarbine
  materials:
    Steel: 2000
    Glass: 800
    Plastic: 500

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponAdvancedLaser
  result: WeaponAdvancedLaser
  materials:
    Steel: 1500
    Glass: 1000
    Gold: 850

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponLaserCannon
  result: WeaponLaserCannon
  materials:
    Steel: 1250
    Plastic: 750
    Gold: 500

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponLaserSvalinn
  result: WeaponLaserSvalinn
  materials:
    Steel: 2000
    Gold: 500

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponXrayCannon
  result: WeaponXrayCannon
  materials:
    Steel: 1500
    Glass: 500
    Plastic: 250
    Gold: 100

- type: latheRecipe
  id: ClothingBackpackElectropack
  result: ClothingBackpackElectropack
  completetime: 4
  materials:
    Steel: 500
    Plastic: 250
    Cloth: 500

- type: latheRecipe
  id: ForensicPad
  result: ForensicPad
  completetime: 4
  materials:
    Plastic: 100

- type: latheRecipe
  id: ClothingEyesHudSecurity
  result: ClothingEyesHudSecurity
  completetime: 2
  materials:
    Steel: 300
    Glass: 200

- type: latheRecipe
  id: HoloprojectorSecurity
  result: HoloprojectorSecurityEmpty
  completetime: 2
  materials:
    Steel: 300
    Glass: 50
    Plastic: 50

- type: latheRecipe
  id: RiotShield
  result: RiotShield
  completetime: 4
  materials:
    Steel: 400
    Glass: 400

- type: latheRecipe
  id: TelescopicShield
  result: TelescopicShield
  completetime: 4
  materials:
    Steel: 300
    Glass: 800

- type: latheRecipe
  id: Flash
  result: Flash
  completetime: 2
  materials:
    Glass: 100
    Plastic: 200
    Steel: 100

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: Box12GaugeTranquilizer
  result: Box12GaugeTranquilizer
  materials:
    Plastic: 240
    Steel: 160
    Glass: 80
    Plasma: 160
    Silver: 80

- type: latheRecipe
  id: TargetHuman
  result: TargetHuman
  completetime: 5
  applyMaterialDiscount: false # ingredients dropped when destroyed
  materials:
    Steel: 500

- type: latheRecipe
  parent: TargetHuman
  id: TargetClown
  result: TargetClown

- type: latheRecipe
  parent: TargetHuman
  id: TargetSyndicate
  result: TargetSyndicate

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: Box12GaugeBuckshot
  result: Box12GaugeBuckshot
  materials:
    Steel: 320

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: Box12GaugeBeanbag
  result: Box12GaugeBeanbag
  materials:
    Steel: 160
    Plastic: 240

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: Box12GaugeSlug
  result: Box12GaugeSlug
  materials:
    Steel: 240
    Plastic: 160

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: SpeedLoader45_magnumEmpty
  result: SpeedLoader45_magnumEmpty
  materials:
    Steel: 50

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: SpeedLoader45_magnum
  result: SpeedLoader45_magnum
  materials:
    Steel: 190

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: SpeedLoader45_magnumPractice
  result: SpeedLoader45_magnumPractice
  materials:
    Steel: 90

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: SpeedLoader45_magnumUranium
  result: SpeedLoader45_magnumUranium
  materials:
    Steel: 50
    Plastic: 150
    Uranium: 110

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: SpeedLoader45_magnumIncendiary
  result: SpeedLoader45_magnumIncendiary
  materials:
    Steel: 50
    Plastic: 150

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: Box12GaugeFlare
  result: Box12GaugeFlare
  materials:
    Steel: 80
    Plastic: 80

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: Box12GaugeIncendiary
  result: Box12GaugeIncendiary
  materials:
    Steel: 80
    Plastic: 320

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponLaserCarbinePractice
  result: WeaponLaserCarbinePractice
  completetime: 6
  materials:
    Steel: 1800
    Glass: 400
    Plastic: 250

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponDisablerPractice
  result: WeaponDisablerPractice
  completetime: 4
  materials:
    Steel: 500
    Glass: 100
    Plastic: 200

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: Box12GaugePractice
  result: Box12GaugePractice
  materials:
    Steel: 80

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: Box12GaugeUranium
  result: Box12GaugeUranium
  materials:
    Plastic: 320
    Uranium: 240

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponFlareGunSecurity
  result: WeaponFlareGunSecurity
  completetime: 6
  materials:
    Plastic: 100
    Steel: 400

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponDisabler
  result: WeaponDisabler
  completetime: 6
  materials:
    Steel: 300
    Glass: 200
    Plastic: 200

- type: latheRecipe
  parent: WeaponDisabler
  id: WeaponDisablerSMG
  result: WeaponDisablerSMG
  materials:
    Steel: 1000
    Glass: 500
    Plastic: 500

- type: latheRecipe
  id: Magazine40mmEmpty
  result: Magazine40mmEmpty
  completetime: 3
  materials:
    Steel: 150
    Plastic: 50

- type: latheRecipe
  id: 40mmGrenadeEMP
  result: 40mmGrenadeEMP
  completetime: 3
  materials:
    Steel: 150
    Plastic: 100
    Glass: 20

- type: latheRecipe
  id: 40mmGrenadeThermobaric
  result: 40mmGrenadeThermobaric
  completetime: 3
  materials:
    Steel: 450
    Plastic: 300
    Gold: 150

- type: latheRecipe
  id: 40mmGrenadeFlash
  result: 40mmGrenadeFlash
  completetime: 3
  materials:
    Steel: 150
    Plastic: 100
    Glass: 20

- type: latheRecipe
  id: PortableRecharger
  result: PortableRecharger
  completetime: 15
  materials:
    Steel: 2000
    Uranium: 2000
    Plastic: 1000
    Plasma: 500
    Glass: 500

# mono changes start

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: Magazine8x65mmEmpty
  result: Magazine8x65mmEmpty
  materials:
    Steel: 30

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: Magazine8x65mmSKR
  result: Magazine8x65mmSKR
  materials:
    Steel: 650

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: AmmoBox8x65mmSKR
  result: AmmoBox8x65mmSKR
  materials:
    Steel: 1200

# mono changes end

# Shitmed Recipes

- type: latheRecipe
  id: SecurityCyberneticEyes
  result: SecurityCyberneticEyes
  completetime: 5
  materials:
    Steel: 1000
    Glass: 500
    Plastic: 500
    Gold: 300
    Silver: 300
