# Base prototypes

- type: latheRecipe
  abstract: true
  id: BaseWeaponRecipe
  categories:
  - Weapons
  completetime: 2
  materials:
    Steel: 300
    Plastic: 300

- type: latheRecipe
  abstract: true
  parent: BaseWeaponRecipe
  id: BaseWeaponRecipeLong
  completetime: 5

- type: latheRecipe
  abstract: true
  id: BaseAmmoRecipe
  categories:
  - Ammo
  completetime: 5

- type: latheRecipe
  abstract: true
  parent: BaseAmmoRecipe
  id: BaseEmptyAmmoRecipe
  completetime: 1

# Recipes

- type: latheRecipe
  id: Handcuffs
  result: Handcuffs
  completetime: 2
  materials:
    Steel: 300

- type: latheRecipe
  id: Zipties
  result: Zipties
  completetime: 2
  materials:
    Plastic: 200

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: Stunbaton
  result: Stunbaton

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: Truncheon
  result: Truncheon

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: CombatKnife
  result: CombatKnife
  materials:
    Steel: 250
    Plastic: 100

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponLaserCarbine
  result: WeaponLaserCarbine
  materials:
    Steel: 2000
    Glass: 800
    Plastic: 500

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponAdvancedLaser
  result: WeaponAdvancedLaser
  materials:
    Steel: 1500
    Glass: 1000
    Gold: 850

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponLaserCannon
  result: WeaponLaserCannon
  materials:
    Steel: 1250
    Plastic: 750
    Gold: 500

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponLaserSvalinn
  result: WeaponLaserSvalinn
  materials:
    Steel: 2000
    Gold: 500

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponXrayCannon
  result: WeaponXrayCannon
  materials:
    Steel: 1500
    Glass: 500
    Plastic: 250
    Gold: 100

- type: latheRecipe
  id: ClothingBackpackElectropack
  result: ClothingBackpackElectropack
  completetime: 4
  materials:
    Steel: 500
    Plastic: 250
    Cloth: 500

- type: latheRecipe
  id: ForensicPad
  result: ForensicPad
  completetime: 4
  materials:
    Plastic: 100

- type: latheRecipe
  id: ClothingEyesHudSecurity
  result: ClothingEyesHudSecurity
  completetime: 2
  materials:
    Steel: 300
    Glass: 200

- type: latheRecipe
  id: HoloprojectorSecurity
  result: HoloprojectorSecurityEmpty
  completetime: 2
  materials:
    Steel: 300
    Glass: 50
    Plastic: 50

- type: latheRecipe
  id: RiotShield
  result: RiotShield
  completetime: 4
  materials:
    Steel: 400
    Glass: 400

- type: latheRecipe
  id: TelescopicShield
  result: TelescopicShield
  completetime: 4
  materials:
    Steel: 300
    Glass: 800

- type: latheRecipe
  id: Flash
  result: Flash
  completetime: 2
  materials:
    Glass: 100
    Plastic: 200
    Steel: 100

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: BoxShellTranquilizer
  result: BoxShellTranquilizer
  materials:
    Plastic: 240
    Steel: 160
    Glass: 80
    Plasma: 160
    Silver: 80

- type: latheRecipe
  id: TargetHuman
  result: TargetHuman
  completetime: 5
  applyMaterialDiscount: false # ingredients dropped when destroyed
  materials:
    Steel: 500

- type: latheRecipe
  parent: TargetHuman
  id: TargetClown
  result: TargetClown

- type: latheRecipe
  parent: TargetHuman
  id: TargetSyndicate
  result: TargetSyndicate

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: Magazine9x19mmEmpty
  result: Magazine9x19mmEmpty
  materials:
    Steel: 25

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: Magazine9x19mm
  result: Magazine9x19mm
  materials:
    Steel: 145

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: Magazine9x19mmPractice
  result: Magazine9x19mmPractice
  materials:
    Steel: 85

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: Magazine9x19mmUranium
  result: Magazine9x19mmUranium
  materials:
    Steel: 25
    Plastic: 65
    Uranium: 120

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: Magazine9x19mmIncendiary
  result: Magazine9x19mmIncendiary
  materials:
    Steel: 25
    Plastic: 120

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: Magazine9x19mmSubMachineGunEmpty
  result: Magazine9x19mmSubMachineGunEmpty
  materials:
    Steel: 30

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: Magazine9x19mmSubMachineGun
  result: Magazine9x19mmSubMachineGun
  materials:
    Steel: 300

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: Magazine9x19mmSubMachineGunUranium
  result: Magazine9x19mmSubMachineGunUranium
  materials:
    Steel: 25
    Plastic: 250
    Uranium: 250

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: Magazine9x19mmSubMachineGunIncendiary
  result: Magazine9x19mmSubMachineGunIncendiary
  materials:
    Steel: 25
    Plastic: 275

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: Magazine9x19mmSubMachineGunTopMountedEmpty
  result: Magazine9x19mmSubMachineGunTopMountedEmpty
  materials:
    Steel: 30

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: Magazine9x19mmSubMachineGunTopMounted
  result: Magazine9x19mmSubMachineGunTopMounted
  materials:
    Steel: 300

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxPistol
  result: MagazineBoxPistol
  materials:
    Steel: 600

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxMagnum
  result: MagazineBoxMagnum
  materials:
    Steel: 240

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazineRifleEmpty
  result: MagazineRifleEmpty
  materials:
    Steel: 25

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineRifle
  result: MagazineRifle
  materials:
    Steel: 475


- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineRiflePractice
  result: MagazineRiflePractice
  materials:
    Steel: 175

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineRifleUranium
  result: MagazineRifleUranium
  materials:
    Steel: 25
    Plastic: 300
    Uranium: 300

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineRifleIncendiary
  result: MagazineRifleIncendiary
  materials:
    Steel: 25
    Plastic: 450

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: Magazine7.62x39mmEmpty
  result: Magazine7.62x39mmEmpty
  materials:
    Steel: 25

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: Magazine7.62x39mm
  result: Magazine7.62x39mm
  materials:
    Steel: 565

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: Magazine7.62x39mmPractice
  result: Magazine7.62x39mmPractice
  materials:
    Steel: 205


- type: latheRecipe
  parent: BaseAmmoRecipe
  id: Magazine7.62x39mmUranium
  result: Magazine7.62x39mmUranium
  materials:
    Steel: 25
    Plastic: 360
    Uranium: 360

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: Magazine7.62x39mmIncendiary
  result: Magazine7.62x39mmIncendiary
  materials:
    Steel: 25
    Plastic: 540

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBox5.56x45mm
  result: MagazineBox5.56x45mm
  materials:
    Steel: 750

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBox7.62x39mm
  result: MagazineBox7.62x39mm
  materials:
    Steel: 900

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: BoxLethalshot
  result: BoxLethalshot
  materials:
    Steel: 320

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: BoxBeanbag
  result: BoxBeanbag
  materials:
    Steel: 160
    Plastic: 240

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: BoxShotgunSlug
  result: BoxShotgunSlug
  materials:
    Steel: 240
    Plastic: 160

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: SpeedLoaderMagnumEmpty
  result: SpeedLoaderMagnumEmpty
  materials:
    Steel: 50

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: SpeedLoaderMagnum
  result: SpeedLoaderMagnum
  materials:
    Steel: 190

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: SpeedLoaderMagnumPractice
  result: SpeedLoaderMagnumPractice
  materials:
    Steel: 90

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: SpeedLoaderMagnumUranium
  result: SpeedLoaderMagnumUranium
  materials:
    Steel: 50
    Plastic: 150
    Uranium: 110

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: SpeedLoaderMagnumIncendiary
  result: SpeedLoaderMagnumIncendiary
  materials:
    Steel: 50
    Plastic: 150

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazineShotgunEmpty
  result: MagazineShotgunEmpty
  materials:
    Steel: 50

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineShotgun
  result: MagazineShotgun
  materials:
    Steel: 240

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineShotgunBeanbag
  result: MagazineShotgunBeanbag
  materials:
    Steel: 150
    Plastic: 140

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineShotgunSlug
  result: MagazineShotgunSlug
  materials:
    Steel: 190
    Plastic: 100

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineShotgunIncendiary
  result: MagazineShotgunIncendiary
  materials:
    Steel: 100
    Plastic: 190

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxPistolIncendiary
  result: MagazineBoxPistolIncendiary
  materials:
    Plastic: 600

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxMagnumIncendiary
  result: MagazineBoxMagnumIncendiary
  materials:
    Plastic: 240

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBox7.62x39mmIncendiary
  result: MagazineBox7.62x39mmIncendiary
  materials:
    Plastic: 900

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBox5.56x45mmIncendiary
  result: MagazineBox5.56x45mmIncendiary
  materials:
    Plastic: 750

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: BoxShotgunFlare
  result: BoxShotgunFlare
  materials:
    Steel: 80
    Plastic: 80

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: BoxShotgunIncendiary
  result: BoxShotgunIncendiary
  materials:
    Steel: 80
    Plastic: 320

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxPistolPractice
  result: MagazineBoxPistolPractice
  materials:
    Steel: 300

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxMagnumPractice
  result: MagazineBoxMagnumPractice
  materials:
    Steel: 60

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBox7.62x39mmPractice
  result: MagazineBox7.62x39mmPractice
  materials:
    Steel: 300

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBox5.56x45mmPractice
  result: MagazineBox5.56x45mmPractice
  materials:
    Steel: 250

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponLaserCarbinePractice
  result: WeaponLaserCarbinePractice
  completetime: 6
  materials:
    Steel: 1800
    Glass: 400
    Plastic: 250

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponDisablerPractice
  result: WeaponDisablerPractice
  completetime: 4
  materials:
    Steel: 500
    Glass: 100
    Plastic: 200

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: BoxShotgunPractice
  result: BoxShotgunPractice
  materials:
    Steel: 80

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxPistolUranium
  result: MagazineBoxPistolUranium
  materials:
    Plastic: 300
    Uranium: 600

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxMagnumUranium
  result: MagazineBoxMagnumUranium
  materials:
    Plastic: 240
    Uranium: 180

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBox7.62x39mmUranium
  result: MagazineBox7.62x39mmUranium
  materials:
    Plastic: 600
    Uranium: 600

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBox5.56x45mmUranium
  result: MagazineBox5.56x45mmUranium
  materials:
    Plastic: 500
    Uranium: 500

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: BoxShotgunUranium
  result: BoxShotgunUranium
  materials:
    Plastic: 320
    Uranium: 240

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponFlareGunSecurity
  result: WeaponFlareGunSecurity
  completetime: 6
  materials:
    Plastic: 100
    Steel: 400

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponDisabler
  result: WeaponDisabler
  completetime: 6
  materials:
    Steel: 300
    Glass: 200
    Plastic: 200

- type: latheRecipe
  parent: WeaponDisabler
  id: WeaponDisablerSMG
  result: WeaponDisablerSMG
  materials:
    Steel: 1000
    Glass: 500
    Plastic: 500

- type: latheRecipe
  id: Magazine40mmEmpty
  result: Magazine40mmEmpty
  completetime: 3
  materials:
    Steel: 150
    Plastic: 50

- type: latheRecipe
  id: GrenadeEMP
  result: GrenadeEMP
  completetime: 3
  materials:
    Steel: 150
    Plastic: 100
    Glass: 20

- type: latheRecipe
  id: GrenadeBlast
  result: GrenadeBlast
  completetime: 3
  materials:
    Steel: 450
    Plastic: 300
    Gold: 150

- type: latheRecipe
  id: GrenadeFlash
  result: GrenadeFlash
  completetime: 3
  materials:
    Steel: 150
    Plastic: 100
    Glass: 20

- type: latheRecipe
  id: PortableRecharger
  result: PortableRecharger
  completetime: 15
  materials:
    Steel: 2000
    Uranium: 2000
    Plastic: 1000
    Plasma: 500
    Glass: 500

# mono changes start

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazineDMREmpty
  result: MagazineDMREmpty
  materials:
    Steel: 30

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineDMR
  result: MagazineDMR
  materials:
    Steel: 650

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxDMR
  result: MagazineBoxDMR
  materials:
    Steel: 1200

# mono changes end

# Shitmed Recipes

- type: latheRecipe
  id: SecurityCyberneticEyes
  result: SecurityCyberneticEyes
  completetime: 5
  materials:
    Steel: 1000
    Glass: 500
    Plastic: 500
    Gold: 300
    Silver: 300
