# Base prototypes can be found in \Resources\Prototypes\Recipes\Lathes\security.yml

# Recipes

- type: latheRecipe # crossbow bolt
  id: CrossbowBolt
  parent: BaseAmmoRecipe
  result: CrossbowBolt
  materials:
    Steel: 20

- type: latheRecipe # crossbow bolt
  id: CrossbowBoltBroadhead
  parent: BaseAmmoRecipe
  result: CrossbowBoltBroadhead
  materials:
    Steel: 25

- type: latheRecipe # novalite mag empty
  id: MagazineNovaliteC1Empty
  parent: BaseEmptyAmmoRecipe
  result: MagazineNovaliteC1Empty
  materials:
    Steel: 20

- type: latheRecipe # novalite mag
  id: MagazineNovaliteC1
  parent: BaseAmmoRecipe
  result: MagazineNovaliteC1
  materials:
    Steel: 245 # 20 [Steel per empty mag] + 15 [bullets] * 15 [Steel per bullet]

- type: latheRecipe # novalite rubber mag
  id: MagazineNovaliteC1Rubber
  parent: BaseAmmoRecipe
  result: MagazineNovaliteC1Rubber
  materials:
    Steel: 82 #33% of 245 in steel
    Plastic: 163 #66% of 245

- type: latheRecipe # gestio mag empty
  id: Magazine7.62x39mmLowCapacityEmpty
  parent: BaseEmptyAmmoRecipe
  result: Magazine7.62x39mmLowCapacityEmpty
  materials:
    Steel: 20
- type: latheRecipe # Gestio small rubber mag
  id: Magazine7.62x39mmLowCapacityRubber
  parent: BaseAmmoRecipe
  result: Magazine7.62x39mmLowCapacityRubber
  materials:
    Steel: 82 #33% of cost in steel
    Plastic: 163 #66% of 245

- type: latheRecipe # gestio mag
  id: Magazine7.62x39mmLowCapacity
  parent: BaseAmmoRecipe
  result: Magazine7.62x39mmLowCapacity
  materials:
    Steel: 245 # 20 [Steel per empty mag] + 15 [bullets] * 15 [Steel per bullet]

- type: latheRecipe
  id: SpeedLoader5.56x45mmEmpty
  parent: BaseEmptyAmmoRecipe
  result: SpeedLoader5.56x45mmEmpty
  materials:
    Steel: 25

- type: latheRecipe
  id: SpeedLoader5.56x45mm
  parent: BaseAmmoRecipe
  result: SpeedLoader5.56x45mm
  materials:
    Steel: 140 # 25 [Steel per empty mag] + 8 [bullets] * 15 [Steel per bullet]

- type: latheRecipe
  id: SpeedLoader5.56x45mmRubber #Argenti rubber loader
  parent: BaseAmmoRecipe
  result: SpeedLoader5.56x45mmRubber
  materials:
    Steel: 47 #33% of cost in Steel
    Plastic: 93 #66% of cost in Plastic

- type: latheRecipe
  id: SpeedLoader5.56x45mmPractice
  parent: BaseAmmoRecipe
  result: SpeedLoader5.56x45mmPractice
  materials:
    Steel: 65 # 25 [Steel per empty mag] + 8 [bullets] * 5 [Steel per practice bullet]

- type: latheRecipe
  id: SpeedLoader5.56x45mmUranium
  parent: BaseAmmoRecipe
  result: SpeedLoader5.56x45mmUranium
  materials:
    Steel: 25 # 25 [Steel per empty mag]
    Plastic: 80 # 8 [bullets] * 10 [Plastic per bullet]
    Uranium: 80 # 8 [bullets] * 10 [Uranium per bullet]

- type: latheRecipe
  id: SpeedLoader5.56x45mmIncendiary
  parent: BaseAmmoRecipe
  result: SpeedLoader5.56x45mmIncendiary
  materials:
    Steel: 25 # 25 [Steel per empty mag]
    Plastic: 120 # 8 [bullets] * 15 [Plastic per bullet]

- type: latheRecipe
  id: Magazine9x19mmRubber
  parent: BaseAmmoRecipe
  result: Magazine9x19mmRubber
  materials:
    Steel: 100 #50% of box cost
    Plastic: 200 #50% of box cost

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: Magazine9x19mmSubMachineGunRubber
  result: Magazine9x19mmSubMachineGunRubber
  materials:
    Steel: 150 #75% of box cost
    Plastic: 300 #75% of box cost

- type: latheRecipe
  id: MagazineBox7.62x39mmRubber
  parent: BaseAmmoRecipe
  result: MagazineBox7.62x39mmRubber
  materials:
    Steel: 300
    Plastic: 600

- type: latheRecipe
  id: Magazine7.62x39mmRubber
  parent: BaseAmmoRecipe
  result: Magazine7.62x39mmRubber
  materials:
    Steel: 150 #50% of ammo box
    Plastic: 300 #50% of ammo box

- type: latheRecipe
  id: MagazineBox.45_magnumRubber
  parent: BaseAmmoRecipe
  result: MagazineBox.45_magnumRubber
  materials:
    Steel: 80
    Plastic: 160

- type: latheRecipe
  id: SpeedLoader.45_magnumRubber
  parent: BaseAmmoRecipe
  result: SpeedLoader.45_magnumRubber
  materials:
    Steel: 40 #50% of ammo box
    Plastic: 80 #50% of ammo box

- type: latheRecipe
  id: MagazineBoxPistolRubber
  parent: BaseAmmoRecipe
  result: MagazineBoxPistolRubber
  materials:
    Steel: 200
    Plastic: 400

- type: latheRecipe
  id: MagazineBox5.56x45mmRubber
  parent: BaseAmmoRecipe
  result: MagazineBox5.56x45mmRubber
  materials:
    Steel: 250
    Plastic: 500

- type: latheRecipe
  id: Magazine5.56x45mmRubber
  parent: BaseAmmoRecipe
  result: Magazine5.56x45mmRubber
  materials:
    Steel: 125 #50% of ammo box
    Plastic: 250 #50% of ammo box

- type: latheRecipe
  id: ShellTranquilizer # Removed upstream
  parent: BaseAmmoRecipe
  result: ShellTranquilizer
  materials:
    Plastic: 15
    Steel: 10
    Glass: 5
    Plasma: 10
    Silver: 5

- type: latheRecipe
  id: WeaponPistolPollock
  result: WeaponPistolPollock
  categories:
  - Weapons
  completetime: 3
  materials:
    Steel: 1000
    Plastic: 1200
    Plasteel: 1200

- type: latheRecipe
  id: ClothingEyesHudNfsd
  parent: ClothingEyesHudSecurity
  result: ClothingEyesHudNfsd

- type: latheRecipe
  id: HoloprojectorNfsd
  parent: ClothingEyesHudSecurity
  result: HoloprojectorNfsdEmpty
