- type: job
  id: USSPCorporal
  name: job-name-ussp-corporal
  description: job-description-ussp-corporal
  playTimeTracker: JobUSSPCorporal
  requirements:
  - !type:DepartmentTimeRequirement
    department: UnionOfSovietSocialistPlanets
    time: 14400 # 4 hours
  - !type:OverallPlaytimeRequirement
    time: 14400 # 4 hrs
  startingGear: USSPCorporalGear
  icon: "JobIconSecurityOfficer" # TODO - new USSP icons
  supervisors: job-supervisors-ussp-sergeant
  canBeAntag: false
  accessGroups:
  - GeneralAccess
  - USSPLow

- type: startingGear
  id: USSPCorporalGear
  equipment:
    pocket1: WeaponPistolPollock
    pocket2: MagazinePistol
  storage:
    back:
    - WeaponRifleAK502
