- type: job
  id: USSPMedic
  name: job-name-ussp-medic
  description: job-description-ussp-medic
  playTimeTracker: JobUSSPMedic
  requirements:
  - !type:DepartmentTimeRequirement
    department: UnionOfSovietSocialistPlanets
    time: 14400 # 4 hours
  - !type:OverallPlaytimeRequirement
    time: 14400 # 4 hrs
  startingGear: USSPMedicGear
  icon: "JobIconBrigmedic" # TODO - new USSP icons
  supervisors: job-supervisors-ussp-sergeant
  canBeAntag: false
  accessGroups:
  - GeneralAccess
  - USSPLow

- type: startingGear
  id: USSPMedicGear
  equipment:
    pocket1: WeaponPistolPollock
    pocket2: MagazinePistol
  storage:
    back:
    - WeaponRifleAK502
