- type: job
  id: USSPSergeant
  name: job-name-ussp-sergeant
  description: job-description-ussp-sergeant
  playTimeTracker: JobUSSPSergeant
  requirements:
  - !type:DepartmentTimeRequirement
    department: UnionOfSovietSocialistPlanets
    time: 54000 # 15 hours
  - !type:OverallPlaytimeRequirement
    time: 72000 # 20 hrs
  startingGear: USSPSergeantGear
  icon: "JobIconSeniorOfficer" # TODO - new USSP icons
  supervisors: job-supervisors-ussp-commissars
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - USSP
  accessGroups:
  - GeneralAccess
  - USSPHigh

- type: startingGear
  id: USSPSergeantGear
  equipment:
    pocket1: WeaponPistolPollock
    pocket2: MagazinePistol
  storage:
    back:
    - WeaponRifleAK502
