# SPDX-FileCopyrightText: 2025 UnicornOnLSD
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: DIEmployee
  name: job-name-di-employee
  description: job-description-di-employee
  playTimeTracker: JobDIEmployee
  startingGear: DIEmployeeGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  icon: "JobIconDIEmployee"
  supervisors: job-supervisors-di-overseer
  canBeAntag: false
  weight: 10
  displayWeight: 10
  accessGroups:
  - GeneralAccess
  - DIEmployeeAccess

- type: startingGear
  id: DIEmployeeGear
