# SPDX-FileCopyrightText: 2025 UnicornOnLSD
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: DIGrunt
  name: job-name-di-grunt
  description: job-description-di-grunt
  playTimeTracker: JobDIGrunt
  startingGear: DIGruntGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  icon: "JobIconDIGrunt"
  supervisors: job-supervisors-di-overseer
  canBeAntag: false
  weight: 10
  displayWeight: 10
  #special:
  # - !type:AddComponentSpecial
    # components:
    # - type: NpcFactionMember
      # factions:
      # - DI
  accessGroups:
  - GeneralAccess
  access:
  - DI

- type: startingGear
  id: DIGruntGear
  equipment:
    pocket1: WeaponPistolMk32
    pocket2: Magazine9x19mmPistolFMJ
