# SPDX-FileCopyrightText: 2025 UnicornOnLSD
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: DIOverseer
  name: job-name-di-overseer
  description: job-description-di-overseer
  playTimeTracker: JobDIOverseer
  requirements:
  - !type:DepartmentTimeRequirement
    department: DrakeIndustries
    time: 18000 # 5 hours
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5 hours
  startingGear: DIOverseerGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  icon: "JobIconDIOverseer"
  supervisors: job-supervisors-di-board
  canBeAntag: false
  weight: 30
  displayWeight: 30
  #special:
  # - !type:AddComponentSpecial
    # components:
    # - type: NpcFactionMember
      # factions:
      # - DI
  accessGroups:
  - GeneralAccess
  - DIAA

- type: startingGear
  id: DIOverseerGear
  equipment:
    pocket1: WeaponPistolMk32
    pocket2: Magazine9x19mmPistolFMJ
