# SPDX-FileCopyrightText: 2025 UnicornOnLSD
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: DIOverseer
  name: job-name-di-overseer
  description: job-description-di-overseer
  playTimeTracker: JobDIOverseer
  requirements:
  - !type:DepartmentTimeRequirement
    department: DrakeIndustries
    time: 18000 # 5 hours
  # - !type:RoleTimeRequirement TODO add for later once faction is settled in proper
      # role: JobDIGrunt
      # time: 3600 # 1 hr
  # - !type:RoleTimeRequirement
      # role: JobDITrucker
      # time: 3600 # 1 hr
  # - !type:RoleTimeRequirement
      # role: JobDIWatchdog
      # time: 3600 # 1 hr
  startingGear: DIOverseerGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  icon: "JobIconDIOverseer"
  supervisors: job-supervisors-di-board
  canBeAntag: false
  weight: 30
  displayWeight: 30
  accessGroups:
  - GeneralAccess
  - DIOverseerAccess

- type: startingGear
  id: DIOverseerGear
  equipment:
    pocket1: WeaponPistolMk32
    pocket2: Magazine9x19mmPistolFMJ
