# SPDX-FileCopyrightText: 2025 UnicornOnLSD
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: DIWatchdog
  name: job-name-di-watchdog
  description: job-description-di-watchdog
  playTimeTracker: JobDIWatchdog
  requirements:
  - !type:RoleTimeRequirement
      role: JobMercenary
      time: 10800 # 3 hours     
  startingGear: DIWatchdogGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  icon: "JobIconDIWatchdog"
  supervisors: job-supervisors-di-overseer
  canBeAntag: false
  weight: 25
  displayWeight: 25
  accessGroups:
  - GeneralAccess
  - DIWatchdogAccess

- type: startingGear
  id: DIWatchdogGear
  equipment:
    pocket1: WeaponPistolMk32
    pocket2: Magazine9x19mmPistolFMJ