## Static recipes

- type: latheRecipePack
  id: SecurityEquipmentStatic
  recipes:
  - ClothingEyesHudSecurity
  - ForensicPad
  - Handcuffs
  - TargetClown
  - TargetHuman
  - TargetSyndicate
  - Zipties

# Practice ammo/mags and practice weapons
- type: latheRecipePack
  id: SecurityPracticeStatic
  recipes:
  - BoxShotgunPractice
  - MagazineBox7.62x39mmPractice
  - MagazineBoxMagnumPractice
  - MagazineBoxPistolPractice
  - MagazineBox5.56x45mmPractice
  - WeaponDisablerPractice
  - WeaponLaserCarbinePractice
  # - WeaponFlareGunSecurity # Frontier

# Shared between secfab and emagged autolathe
- type: latheRecipePack
  id: SecurityAmmoStatic
  recipes:
  - BoxLethalshot
  - BoxShotgunSlug
  - MagazineBox7.62x39mm
  - MagazineBox7.62x39mmRubber # Frontier
  - MagazineBoxMagnum
  - MagazineBoxMagnumRubber # Frontier
  - MagazineBoxPistol
  - MagazineBoxPistolRubber # Frontier
  - MagazineBox5.56x45mm
  - MagazineBox5.56x45mmRubber # Frontier
  - Magazine7.62x39mm
  - Magazine7.62x39mmRubber # Frontier
  - Magazine7.62x39mmEmpty
  - MagazinePistol
  - MagazinePistolRubber # Frontier
  - MagazinePistolEmpty
  - MagazinePistolSubMachineGun
  - MagazinePistolSubMachineGunRubber # Frontier
  - MagazinePistolSubMachineGunEmpty
  - MagazinePistolSubMachineGunTopMounted
  - MagazinePistolSubMachineGunTopMountedEmpty
  - MagazineRifle
  - MagazineRifleEmpty
  - MagazineShotgun
  - MagazineShotgunEmpty
  - MagazineShotgunSlug
  - SpeedLoaderMagnum
  - SpeedLoaderMagnumEmpty
  - SpeedLoader5.56x45mm # Frontier
  - SpeedLoader5.56x45mmEmpty # Frontier
  - MagazineNovaliteC1Empty # Frontier
  - MagazineNovaliteC1 # Frontier
  - MagazineNovaliteC1Rubber # Frontier
  - MagazineDMR # mono
  - MagazineDMREmpty # mono
  - MagazineBoxDMR # mono
  - Magazine7.62x39mmLowCapacity # mono

- type: latheRecipePack
  id: SecurityWeaponsStatic
  recipes:
  - Flash
  - Stunbaton
  - CombatKnife
  - RiotShield

## Dynamic recipes

- type: latheRecipePack
  id: SecurityEquipment
  recipes:
  - ClothingBackpackElectropack
  - HoloprojectorSecurity
  - PortableRecharger
  - PowerCageHigh
  - PowerCageMedium
  - PowerCageSmall
  - TelescopicShield

- type: latheRecipePack
  id: SecurityBoards
  abstract: true # Frontier: finally, spammable shuttle guns
  recipes:
  - ShuttleGunDusterCircuitboard
  - ShuttleGunFriendshipCircuitboard
  - ShuttleGunPerforatorCircuitboard
  - ShuttleGunSvalinnMachineGunCircuitboard

- type: latheRecipePack
  parent:
  - ScienceExplosives # sec gets everything for modular grenade making that sci does
  id: SecurityExplosives
  recipes:
  - ExplosivePayload
  - GrenadeBlast
  - GrenadeEMP
  - GrenadeFlash
  - MagazineGrenadeEmpty

# Shared between secfab and emagged protolathe
- type: latheRecipePack
  id: SecurityAmmo
  recipes:
  - BoxBeanbag
  # - BoxShotgunIncendiary # Frontier
  # - BoxShotgunUranium # Frontier
  - BoxShellTranquilizer
  # - MagazineBox7.62x39mmIncendiary # Frontier
  # - MagazineBox7.62x39mmUranium # Frontier
  # - MagazineBoxMagnumIncendiary # Frontier
  # - MagazineBoxMagnumUranium # Frontier
  # - MagazineBoxPistolIncendiary # Frontier
  # - MagazineBoxPistolUranium # Frontier
  # - MagazineBox5.56x45mmIncendiary # Frontier
  # - MagazineBox5.56x45mmUranium # Frontier
  # - Magazine7.62x39mmIncendiary # Frontier
  # - Magazine7.62x39mmUranium # Frontier
  # - MagazinePistolIncendiary # Frontier
  # - MagazinePistolUranium # Frontier
  # - MagazinePistolSubMachineGunIncendiary # Frontier
  # - MagazinePistolSubMachineGunUranium # Frontier
  # - MagazineRifleIncendiary # Frontier
  # - MagazineRifleUranium # Frontier
  - MagazineShotgunBeanbag
  # - MagazineShotgunIncendiary # Frontier
  # - SpeedLoaderMagnumIncendiary # Frontier
  # - SpeedLoaderMagnumUranium # Frontier

- type: latheRecipePack
  id: SecurityWeapons
  recipes:
  - Truncheon
  - WeaponAdvancedLaser
  - WeaponLaserCannon
  - WeaponLaserCarbine
  - WeaponXrayCannon

- type: latheRecipePack
  id: SecurityDisablers
  recipes:
  - WeaponDisabler
  - WeaponDisablerSMG

# WD EDIT START
- type: latheRecipePack
  id: VisionGoggles
  recipes:
  - ClothingEyesNightVisionGoggles
  - ClothingEyesThermalVisionGoggles
# WD EDIT END
